charts/argus/Chart.yaml
charts/argus/templates/_helpers.tpl
charts/argus/templates/deployment.yaml
charts/collectorset-controller/Chart.yaml
charts/collectorset-controller/templates/_helpers.tpl
charts/collectorset-controller/templates/deployment.yaml
charts/collectorset-controller/values.schema.json
charts/collectorset-controller/values.yaml

Trigger pod restart on configmap change
Enable Pod Container Probe for collectorset controller only on 1.24+ versions

feat(csc,argus): enable cj, jobs, pvc for monitoring 

---

charts/collectorset-controller/Chart.yaml
charts/collectorset-controller/templates/collector-rbac.yaml

added node metrics permissions in collector

feat(permissions): added node metrics permissions

---

charts/lm-container/Chart.yaml

updating chart version for csc and lm-container

feat(chart): updating chart version

---

charts/argus/Chart.yaml
charts/lm-container/Chart.yaml

fixed issue with namespace recreation and deletion

fix(namespace recreate issue): fixed issue with namespace recreation

---

charts/argus/Chart.yaml
charts/lm-container/Chart.yaml

upgraded container chart version

fix(container chart): upgraded container chart version

---

charts/argus/Chart.yaml
charts/lm-container/Chart.yaml

fix(selector in pdb): support for selectors in pdb

---

charts/lm-container/Chart.yaml

Co-authored-by: Sagar Mamdapure <sagar.mamdapure@logicmonitor.com>

fix(security): fixed security vulnerabilities (#74)

---

charts/lm-container/Chart.yaml

fix(argus): argus version upgrade

---

charts/argus/Chart.yaml
charts/argus/templates/rbac.yaml
charts/collectorset-controller/Chart.yaml
charts/collectorset-controller/templates/collector-rbac.yaml

Changes done in charts to add support for clusterrole and clusterrolebindings

feat(argus): added support for clusterrole and clusterrolebindings

---

charts/lm-container/Chart.yaml

fix(lm-container): updated charts

---

charts/lmutil/Chart.yaml
charts/lmutil/templates/_customizations.tpl
charts/lmutil/templates/_util.tpl

to prefer user provided values over default values

feat(lmutil): alter default and custom templates

---

charts/lm-container/Chart.yaml

fix(lm-container): updated chart version

---

charts/argus/Chart.yaml
charts/argus/templates/collectorset.yaml
charts/argus/values.schema.json
charts/argus/values.yaml
charts/collectorset-controller/Chart.yaml
charts/collectorset-controller/crds/collectorset.yaml

Added schema for affinity param for collector pod.

feat(affinity-rule): configurable affinity rule

---

charts/lm-container/Chart.yaml

Container charts for affinity rule configuration

feat(affinity-rule): container charts for affinity rule configuration

---

charts/collectorset-controller/Chart.yaml
charts/collectorset-controller/templates/collector-rbac.yaml

Fixed rbac permissions for replicasets, daemonsets & statefulsets

fix(rbac): rbac permissions

---

charts/lm-container/Chart.yaml

update chart version for configurable affinity rule

feat(lmc-4.0.0-rc03): update chart version for configurable affinity rule

---

charts/argus/Chart.yaml
charts/collectorset-controller/Chart.yaml

We've already bumped up the Argus and CSC helm chart versions in the previous PR's

feat(argus,csc): base os upgrade

---

charts/lm-container/Chart.yaml
charts/lm-container/values.schema.json
charts/lm-container/values.yaml

Integrates `lmotel` helm chart with `lm-container` chart.

feat(lmc, lmotel): integrate-lmotel-helm-chart-with-lmcontainer

---

charts/lm-container/Chart.yaml

fix(lmc): argus version bump up

---

charts/lm-logs/Chart.yaml
charts/lm-logs/README.md

upgrade lm-logs chart for lmc so that we can install lm-logs with umbrella chart.

feat( lmc, lm-logs): upgrade lm-logs chart for lmc

---

charts/lm-container/Chart.yaml

Bump up lm-logs to rt version  0.4.0.-rt01 for umbrella chart

feat( lm-container): upgrade lm-logs chart to 0.4.0.-rt01

---

charts/lm-logs/Chart.yaml
charts/lm-logs/Dockerfile
charts/lm-logs/templates/configmap.yaml
charts/lm-logs/values.schema.json
charts/lm-logs/values.yaml

Bearer token support for lm-logs chart.
Support bearer token for authentication with LogicMonitor with lm-logs. 
Bump up lm-logs chart version, app version.

feat(lm-logs): support bearer token for authentication

---

charts/argus/Chart.yaml
charts/argus/templates/_collector.tpl
charts/argus/templates/collectorset.yaml

COLLECTOR_NON_ROOT prop case sensitive check

chore(argus): cOLLECTOR_NON_ROOT prop case sensitive check

---

charts/argus/Chart.yaml

logsource integration with argus

feat(argus): logsource integration

---

charts/lm-container/Chart.yaml

lmc-version-bump-up for logsources

feat(lmc): lmc-version-bump-up for logsources

---

charts/lm-container/Chart.yaml

fix(lmc): lmc-version-bump

---

charts/lm-container/Chart.yaml

Use fluentd config labels to route timed out logs
to the same processing label

fix(lm-logs): update lm-container with lm-logs

---

.github/workflows/add-release-assets.yml

updated workflow to generate json ui template on every release

fix(ui-json): updated workflow to generate json ui template on every release

---

charts/lm-logs/Chart.yaml
charts/lm-logs/templates/_helpers.tpl
charts/lm-logs/templates/configmap.yaml
charts/lm-logs/values.yaml

change user-agent to lm-logs-fluentd-k8s.
Upgrade base image to 1.2.0.

ci(lm-logs): change user-agent

---

charts/argus/Chart.yaml
charts/collectorset-controller/Chart.yaml

argus csc charts for base image upgrade

feat(base-img): argus csc charts for base image upgrade

---

charts/argus/Chart.yaml
charts/argus/templates/deployment.yaml
charts/argus/values.schema.json
charts/argus/values.yaml

fix(upgrade-hotfix): fixed upgrade issue on argus replica param validation

---

charts/argus/Chart.yaml

feat(ksm-filter): argus charts to ignore KSM resources from filter evaluation

---

charts/lm-container/Chart.yaml

feat(filters): lmc charts v8.3.1-rc02

---

charts/argus/Chart.yaml

feat(argus): version upgrade

---

charts/lm-container/Chart.yaml

- Upgrade `lm-container` version

feat(lmc): upgrade lmc version

---

.github/CODEOWNERS

feat(codeowners): updated codeowners

---

charts/argus/Chart.yaml
charts/collectorset-controller/Chart.yaml

- Base image upgrades
- Argus : `v16.0.0-rc01`
- CSC : `v13.0.0-rc01`

feat(version): base image upgrade

---

charts/lm-container/Chart.yaml

- `lm-container` version upgrade to `10.0.0-rc01`
- Argus : `12.0.0-rc01`
- CSC : `11.0.0-rc01`

feat(lmc): lmc version upgrade

---

charts/argus/Chart.yaml
charts/collectorset-controller/Chart.yaml

Argus, csc upgrades
- Argus : `v16.0.0-rc02`
- CSC : `v13.0.0-rc03`

feat(version): argus,csc upgrades

---

charts/argus/Chart.yaml
charts/argus/templates/_filter_config.tpl
charts/argus/templates/_helpers.tpl
charts/argus/values.schema.json

- Fixed toggle issue in batchfilters for ephemeral resources
- `Essential` & `Essentials` synonyms added for setting the `Minimal` mode

feat(filters): fix batchfiltering

---

charts/lm-container/Chart.yaml

- Upgraded argus version to `13.2.0-rc02` and lm-conatiner version to `11.3.0-rc02`

feat(lmc): lmc and argus version upgrade

---

charts/argus/Chart.yaml

- Upgraded argus version to `13.2.0-rt01`

feat(argus): argus version upgrade

---

charts/lm-container/Chart.yaml

* Upgrading the ksm version to 5.36.0. in lm-container helm chart.

feat(lmc): ksm version upgrade in lm-container

---

.github/CODEOWNERS

- added `lm-moulika-kulkarni` to argus charts

chore(owners): updated moulika for argus charts

---

charts/lm-container/Chart.yaml

feat(lmlogs): logs version upgrade to 0.8.0-rc01 in lm-container

feat(lmlogs): logs version upgrade in lm-container

---

charts/argus/Chart.yaml
charts/argus/templates/_helpers.tpl
charts/argus/templates/deployment.yaml
charts/argus/templates/post-install.yaml
charts/argus/templates/rbac.yaml
charts/collectorset-controller/Chart.yaml
charts/collectorset-controller/templates/_helpers.tpl
charts/collectorset-controller/templates/csc-rbac.yaml
charts/collectorset-controller/templates/deployment.yaml
charts/collectorset-controller/templates/post-install.yaml

- This PR adds an alternative to the Helm lookup function to ensure chart compatibility in environments where lookup is not available.

feat(lookup): removed lookup

---

charts/argus/Chart.yaml
charts/argus/templates/post-install.yaml

fix(lookup): ksm url update

---

charts/argus/Chart.yaml
charts/argus/templates/post-install.yaml

fix(lookup): slashes removal

---

charts/lm-container/Chart.yaml

fix(lookup): lmc upgrade
